<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAnmsHwz\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAnmsHwz/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAnmsHwz.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAnmsHwz\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAnmsHwz\App_KernelProdContainer([
    'container.build_hash' => 'AnmsHwz',
    'container.build_id' => '792e05e7',
    'container.build_time' => 1654167632,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAnmsHwz');
