<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'fos_js_routing_js' => [['_format'], ['_controller' => 'fos_js_routing.controller::indexAction', '_format' => 'js'], ['_format' => 'js|json'], [['variable', '.', 'js|json', '_format', true], ['text', '/js/routing']], [], [], []],
    'app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/']], [], [], []],
    'app_p_d_f' => [[], ['_controller' => 'App\\Controller\\PDFController::index'], [], [['text', '/p/d/f']], [], [], []],
    'RegistrarPost' => [[], ['_controller' => 'App\\Controller\\PostsController::index'], [], [['text', '/registrar-post']], [], [], []],
    'verPost' => [['id'], ['_controller' => 'App\\Controller\\PostsController::verPosts'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/verPost']], [], [], []],
    'misPosts' => [[], ['_controller' => 'App\\Controller\\PostsController::misPosts'], [], [['text', '/misPosts']], [], [], []],
    'app_posts_crud_index' => [[], ['_controller' => 'App\\Controller\\PostsCrudController::index'], [], [['text', '/posts/crud/']], [], [], []],
    'app_posts_crud_new' => [[], ['_controller' => 'App\\Controller\\PostsCrudController::new'], [], [['text', '/posts/crud/new']], [], [], []],
    'app_posts_crud_show' => [['id'], ['_controller' => 'App\\Controller\\PostsCrudController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/posts/crud']], [], [], []],
    'app_posts_crud_edit' => [['id'], ['_controller' => 'App\\Controller\\PostsCrudController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/posts/crud']], [], [], []],
    'app_posts_crud_delete' => [['id'], ['_controller' => 'App\\Controller\\PostsCrudController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/posts/crud']], [], [], []],
    'app_registro' => [[], ['_controller' => 'App\\Controller\\RegistroController::index'], [], [['text', '/registro']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_user_crud_index' => [[], ['_controller' => 'App\\Controller\\UserCrudController::index'], [], [['text', '/user/crud/']], [], [], []],
    'app_user_crud_pdf' => [[], ['_controller' => 'App\\Controller\\UserCrudController::pdf'], [], [['text', '/user/crud/pdf']], [], [], []],
    'app_user_crud_new' => [[], ['_controller' => 'App\\Controller\\UserCrudController::new'], [], [['text', '/user/crud/new']], [], [], []],
    'app_user_crud_show' => [['id'], ['_controller' => 'App\\Controller\\UserCrudController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/crud']], [], [], []],
    'app_user_crud_edit' => [['id'], ['_controller' => 'App\\Controller\\UserCrudController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/user/crud']], [], [], []],
    'app_user_crud_delete' => [['id'], ['_controller' => 'App\\Controller\\UserCrudController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/user/crud']], [], [], []],
];
