<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU06nP1J\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU06nP1J/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU06nP1J.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU06nP1J\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerU06nP1J\App_KernelDevDebugContainer([
    'container.build_hash' => 'U06nP1J',
    'container.build_id' => 'fb823699',
    'container.build_time' => 1653950349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU06nP1J');
