<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI6dzMzy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI6dzMzy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI6dzMzy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI6dzMzy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI6dzMzy\App_KernelDevDebugContainer([
    'container.build_hash' => 'I6dzMzy',
    'container.build_id' => '9ce5ca53',
    'container.build_time' => 1654180561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI6dzMzy');
