<?php

namespace ContainerAnmsHwz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComentariosRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ComentariosRepository' shared autowired service.
     *
     * @return \App\Repository\ComentariosRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ComentariosRepository'] = new \App\Repository\ComentariosRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
