<?php

namespace ContainerAnmsHwz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostsTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\PostsType' shared autowired service.
     *
     * @return \App\Form\PostsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\PostsType'] = new \App\Form\PostsType();
    }
}
